#!/usr/bin/env bash

usage_message="Usage: sh $0 generate models free/standard/professional"

function main {
    local SUBCOMMAND="$1"

    case $SUBCOMMAND in
        generate)
            shift  # Remove SUBCOMMAND (generate) argument
            generate "$@"  # Pass the remaining arguments to the generate function
            ;;
        *)
          invalidArgument "$SUBCOMMAND"
    esac
}

function generate {
    local arg="$1"

    case $arg in
        models)
            shift  # Remove "models" argument
            getGenerateVal "$@"
            ;;
        *)
          invalidArgument "$arg"
    esac
}

function getGenerateVal() {
    local arg="$1"

    case $arg in
        free|standard|professional)
            mvn -P "$arg" -pl ./engine/ --also-make clean package -DskipGenerateModels=false -DskipTests=true
            ;;
        *)
          invalidArgument "$arg"
    esac
}

function invalidArgument {
  echo "Invalid argument: $1"
  echo $usage_message
  exit 1
}

main "$@"
