FROM maven:3.8.5-openjdk-8 as maven-build

WORKDIR /e2e/
COPY . .
RUN mvn clean install -DskipTests

FROM openjdk:8-alpine

ARG JAR_FILE=target/e2e-testing-tool.jar

WORKDIR /e2e/

COPY --from=maven-build /e2e/${JAR_FILE} app.jar

ENTRYPOINT ["java", "-DTESTING_IN_PIPELINE=true", "-jar", "app.jar"]