ARG APP_VERSION=0.0.0

FROM openjdk:17-ea-18-jdk-nanoserver-1809

ARG APP_VERSION
RUN echo Container version: %APP_VERSION%

WORKDIR C:/testlum

COPY engine/target/testlum-${APP_VERSION}.jar C:/testlum/testlum-final.jar

ENTRYPOINT ["java", "-jar", "C:\\testlum\\testlum-final.jar"]
