FROM maven:3.9.6-eclipse-temurin-17 AS maven-build

ARG PROFILE

WORKDIR /testlum/
COPY . .
RUN mvn clean install -DskipTests -P$PROFILE

FROM eclipse-temurin:17.0.10_7-jdk

ARG JAR_FILE=target/testlum-1.0.2.jar

WORKDIR /testlum/

COPY --from=maven-build /testlum/engine/${JAR_FILE} testlum.jar

ENTRYPOINT ["java", "-DTESTING_IN_PIPELINE=true", "-jar", "testlum.jar"]
