FROM maven:3.8.6-jdk-11 as maven-build

ARG PROFILE

WORKDIR /testlum/
COPY . .
RUN mvn clean install -DskipTests -P$PROFILE

FROM eclipse-temurin:11.0.28_6-jdk

ARG JAR_FILE=target/testlum-with-dependencies.jar

WORKDIR /testlum/

COPY --from=maven-build /testlum/engine/${JAR_FILE} testlum.jar

ENTRYPOINT ["java", "-DTESTING_IN_PIPELINE=true", "-jar", "testlum.jar"]