#!/usr/bin/env bash

pathPattern='^(-g=|--generate=)(./|/|(./[a-zA-Z0-9_-]+)|(/[a-zA-Z0-9_-]+))+$'

dockerImageName=$1
pathToFolder=$2

function main() {
    if [[ -n "$dockerImageName" ]] && [[ $pathToFolder =~ $pathPattern ]];
    then
      run_docker_locally
    else
      print_error_message
    fi
}

function run_docker_locally() {
  local path
  path=$(get_path)
  mkdir "$path"
  docker run --rm --mount type=bind,source="$path",target="$path" "$dockerImageName" "$pathToFolder"
}

function get_path() {
    echo "$pathToFolder" | perl -pe 's/^(-g=|--generate=)//'
}

function print_error_message() {
    echo "
    Incorrect input of arguments. You must pass 2 arguments:

    1) Cost-Optimization-Testing-Tool docker image name.

    2) Path to initial structure generation.
           Use one of the options: -g={path-to-initial-structure) or --generate={path-to-initial-structure)

    Example: cott -g=/user/folder/generate

             or

             cott --generate=/user/folder/generate
    "
    exit 1
}
main