//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.08 at 09:58:30 AM EEST 
//


package com.knubisoft.e2e.testing.model.scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for horizontal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="horizontal"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="direction" use="required" type="{http://www.knubisoft.com/e2e/testing/model/scenario}scrollHorizontalDir" /&gt;
 *       &lt;attribute name="by" use="required" type="{http://www.knubisoft.com/e2e/testing/model/scenario}scrollBy" /&gt;
 *       &lt;attribute name="value" use="required" type="{http://www.knubisoft.com/e2e/testing/model/scenario}nonEmptyString" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "horizontal")
public class Horizontal {

    @XmlAttribute(name = "direction", required = true)
    protected ScrollHorizontalDir direction;
    @XmlAttribute(name = "by", required = true)
    protected ScrollBy by;
    @XmlAttribute(name = "value", required = true)
    protected String value;

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link ScrollHorizontalDir }
     *     
     */
    public ScrollHorizontalDir getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScrollHorizontalDir }
     *     
     */
    public void setDirection(ScrollHorizontalDir value) {
        this.direction = value;
    }

    /**
     * Gets the value of the by property.
     * 
     * @return
     *     possible object is
     *     {@link ScrollBy }
     *     
     */
    public ScrollBy getBy() {
        return by;
    }

    /**
     * Sets the value of the by property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScrollBy }
     *     
     */
    public void setBy(ScrollBy value) {
        this.by = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
