//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.05 at 10:36:23 PM EEST 
//


package com.knubisoft.e2e.testing.model.scenario;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.knubisoft.e2e.testing.model.scenario package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.knubisoft.e2e.testing.model.scenario
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Scenario }
     * 
     */
    public Scenario createScenario() {
        return new Scenario();
    }

    /**
     * Create an instance of {@link Overview }
     * 
     */
    public Overview createOverview() {
        return new Overview();
    }

    /**
     * Create an instance of {@link Tags }
     * 
     */
    public Tags createTags() {
        return new Tags();
    }

    /**
     * Create an instance of {@link Include }
     * 
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link Auth }
     * 
     */
    public Auth createAuth() {
        return new Auth();
    }

    /**
     * Create an instance of {@link Repeat }
     * 
     */
    public Repeat createRepeat() {
        return new Repeat();
    }

    /**
     * Create an instance of {@link Ui }
     * 
     */
    public Ui createUi() {
        return new Ui();
    }

    /**
     * Create an instance of {@link Http }
     * 
     */
    public Http createHttp() {
        return new Http();
    }

    /**
     * Create an instance of {@link Migrate }
     * 
     */
    public Migrate createMigrate() {
        return new Migrate();
    }

    /**
     * Create an instance of {@link Postgres }
     * 
     */
    public Postgres createPostgres() {
        return new Postgres();
    }

    /**
     * Create an instance of {@link Mysql }
     * 
     */
    public Mysql createMysql() {
        return new Mysql();
    }

    /**
     * Create an instance of {@link Oracle }
     * 
     */
    public Oracle createOracle() {
        return new Oracle();
    }

    /**
     * Create an instance of {@link Mongo }
     * 
     */
    public Mongo createMongo() {
        return new Mongo();
    }

    /**
     * Create an instance of {@link Redis }
     * 
     */
    public Redis createRedis() {
        return new Redis();
    }

    /**
     * Create an instance of {@link Rabbit }
     * 
     */
    public Rabbit createRabbit() {
        return new Rabbit();
    }

    /**
     * Create an instance of {@link Kafka }
     * 
     */
    public Kafka createKafka() {
        return new Kafka();
    }

    /**
     * Create an instance of {@link S3 }
     * 
     */
    public S3 createS3() {
        return new S3();
    }

    /**
     * Create an instance of {@link Sqs }
     * 
     */
    public Sqs createSqs() {
        return new Sqs();
    }

    /**
     * Create an instance of {@link Clickhouse }
     * 
     */
    public Clickhouse createClickhouse() {
        return new Clickhouse();
    }

    /**
     * Create an instance of {@link Elasticsearch }
     * 
     */
    public Elasticsearch createElasticsearch() {
        return new Elasticsearch();
    }

    /**
     * Create an instance of {@link Sendgrid }
     * 
     */
    public Sendgrid createSendgrid() {
        return new Sendgrid();
    }

    /**
     * Create an instance of {@link Ses }
     * 
     */
    public Ses createSes() {
        return new Ses();
    }

    /**
     * Create an instance of {@link Dynamo }
     * 
     */
    public Dynamo createDynamo() {
        return new Dynamo();
    }

    /**
     * Create an instance of {@link Var }
     * 
     */
    public Var createVar() {
        return new Var();
    }

    /**
     * Create an instance of {@link Wait }
     * 
     */
    public Wait createWait() {
        return new Wait();
    }

    /**
     * Create an instance of {@link Invoke }
     * 
     */
    public Invoke createInvoke() {
        return new Invoke();
    }

    /**
     * Create an instance of {@link Shell }
     * 
     */
    public Shell createShell() {
        return new Shell();
    }

    /**
     * Create an instance of {@link ExcelCommands }
     * 
     */
    public ExcelCommands createExcelCommands() {
        return new ExcelCommands();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Click }
     * 
     */
    public Click createClick() {
        return new Click();
    }

    /**
     * Create an instance of {@link Javascript }
     * 
     */
    public Javascript createJavascript() {
        return new Javascript();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link Navigate }
     * 
     */
    public Navigate createNavigate() {
        return new Navigate();
    }

    /**
     * Create an instance of {@link DropDown }
     * 
     */
    public DropDown createDropDown() {
        return new DropDown();
    }

    /**
     * Create an instance of {@link OneValue }
     * 
     */
    public OneValue createOneValue() {
        return new OneValue();
    }

    /**
     * Create an instance of {@link AllValues }
     * 
     */
    public AllValues createAllValues() {
        return new AllValues();
    }

    /**
     * Create an instance of {@link Assert }
     * 
     */
    public Assert createAssert() {
        return new Assert();
    }

    /**
     * Create an instance of {@link Clear }
     * 
     */
    public Clear createClear() {
        return new Clear();
    }

    /**
     * Create an instance of {@link CloseSecondTab }
     * 
     */
    public CloseSecondTab createCloseSecondTab() {
        return new CloseSecondTab();
    }

    /**
     * Create an instance of {@link SendRmqMessage }
     * 
     */
    public SendRmqMessage createSendRmqMessage() {
        return new SendRmqMessage();
    }

    /**
     * Create an instance of {@link ReceiveRmqMessage }
     * 
     */
    public ReceiveRmqMessage createReceiveRmqMessage() {
        return new ReceiveRmqMessage();
    }

    /**
     * Create an instance of {@link RmqHeaders }
     * 
     */
    public RmqHeaders createRmqHeaders() {
        return new RmqHeaders();
    }

    /**
     * Create an instance of {@link RmqHeader }
     * 
     */
    public RmqHeader createRmqHeader() {
        return new RmqHeader();
    }

    /**
     * Create an instance of {@link SendKafkaMessage }
     * 
     */
    public SendKafkaMessage createSendKafkaMessage() {
        return new SendKafkaMessage();
    }

    /**
     * Create an instance of {@link ReceiveKafkaMessage }
     * 
     */
    public ReceiveKafkaMessage createReceiveKafkaMessage() {
        return new ReceiveKafkaMessage();
    }

    /**
     * Create an instance of {@link KafkaHeaders }
     * 
     */
    public KafkaHeaders createKafkaHeaders() {
        return new KafkaHeaders();
    }

    /**
     * Create an instance of {@link KafkaHeader }
     * 
     */
    public KafkaHeader createKafkaHeader() {
        return new KafkaHeader();
    }

    /**
     * Create an instance of {@link Break }
     * 
     */
    public Break createBreak() {
        return new Break();
    }

    /**
     * Create an instance of {@link Get }
     * 
     */
    public Get createGet() {
        return new Get();
    }

    /**
     * Create an instance of {@link Post }
     * 
     */
    public Post createPost() {
        return new Post();
    }

    /**
     * Create an instance of {@link Put }
     * 
     */
    public Put createPut() {
        return new Put();
    }

    /**
     * Create an instance of {@link Patch }
     * 
     */
    public Patch createPatch() {
        return new Patch();
    }

    /**
     * Create an instance of {@link Trace }
     * 
     */
    public Trace createTrace() {
        return new Trace();
    }

    /**
     * Create an instance of {@link Delete }
     * 
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHead() {
        return new Head();
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Multipart }
     * 
     */
    public Multipart createMultipart() {
        return new Multipart();
    }

    /**
     * Create an instance of {@link ElasticsearchGetRequest }
     * 
     */
    public ElasticsearchGetRequest createElasticsearchGetRequest() {
        return new ElasticsearchGetRequest();
    }

    /**
     * Create an instance of {@link ElasticsearchPostRequest }
     * 
     */
    public ElasticsearchPostRequest createElasticsearchPostRequest() {
        return new ElasticsearchPostRequest();
    }

    /**
     * Create an instance of {@link ElasticsearchPutRequest }
     * 
     */
    public ElasticsearchPutRequest createElasticsearchPutRequest() {
        return new ElasticsearchPutRequest();
    }

    /**
     * Create an instance of {@link ElasticsearchPatchRequest }
     * 
     */
    public ElasticsearchPatchRequest createElasticsearchPatchRequest() {
        return new ElasticsearchPatchRequest();
    }

    /**
     * Create an instance of {@link ElasticsearchTraceRequest }
     * 
     */
    public ElasticsearchTraceRequest createElasticsearchTraceRequest() {
        return new ElasticsearchTraceRequest();
    }

    /**
     * Create an instance of {@link ElasticsearchDeleteRequest }
     * 
     */
    public ElasticsearchDeleteRequest createElasticsearchDeleteRequest() {
        return new ElasticsearchDeleteRequest();
    }

    /**
     * Create an instance of {@link ElasticsearchHeadRequest }
     * 
     */
    public ElasticsearchHeadRequest createElasticsearchHeadRequest() {
        return new ElasticsearchHeadRequest();
    }

    /**
     * Create an instance of {@link ElasticsearchOptionsRequest }
     * 
     */
    public ElasticsearchOptionsRequest createElasticsearchOptionsRequest() {
        return new ElasticsearchOptionsRequest();
    }

    /**
     * Create an instance of {@link ElasticSearchResponse }
     * 
     */
    public ElasticSearchResponse createElasticSearchResponse() {
        return new ElasticSearchResponse();
    }

    /**
     * Create an instance of {@link ElasticSearchResponseWarning }
     * 
     */
    public ElasticSearchResponseWarning createElasticSearchResponseWarning() {
        return new ElasticSearchResponseWarning();
    }

    /**
     * Create an instance of {@link SesMessage }
     * 
     */
    public SesMessage createSesMessage() {
        return new SesMessage();
    }

    /**
     * Create an instance of {@link SesBody }
     * 
     */
    public SesBody createSesBody() {
        return new SesBody();
    }

    /**
     * Create an instance of {@link SesTextContent }
     * 
     */
    public SesTextContent createSesTextContent() {
        return new SesTextContent();
    }

    /**
     * Create an instance of {@link SendgridGet }
     * 
     */
    public SendgridGet createSendgridGet() {
        return new SendgridGet();
    }

    /**
     * Create an instance of {@link SendgridPost }
     * 
     */
    public SendgridPost createSendgridPost() {
        return new SendgridPost();
    }

    /**
     * Create an instance of {@link SendgridPut }
     * 
     */
    public SendgridPut createSendgridPut() {
        return new SendgridPut();
    }

    /**
     * Create an instance of {@link SendgridPatch }
     * 
     */
    public SendgridPatch createSendgridPatch() {
        return new SendgridPatch();
    }

    /**
     * Create an instance of {@link SendgridDelete }
     * 
     */
    public SendgridDelete createSendgridDelete() {
        return new SendgridDelete();
    }

    /**
     * Create an instance of {@link When }
     * 
     */
    public When createWhen() {
        return new When();
    }

    /**
     * Create an instance of {@link PostgresResult }
     * 
     */
    public PostgresResult createPostgresResult() {
        return new PostgresResult();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Logout }
     * 
     */
    public Logout createLogout() {
        return new Logout();
    }

}
