//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.28 at 07:19:11 PM EET 
//


package com.knubisoft.e2e.testing.model.scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for postgresResult complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="postgresResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.knubisoft.com/e2e/testing/model/scenario}abstractCommand"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="query" type="{http://www.knubisoft.com/e2e/testing/model/scenario}variableQuery"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="file" type="{http://www.knubisoft.com/e2e/testing/model/scenario}nonEmptyString" /&gt;
 *       &lt;attribute name="databaseName" use="required" type="{http://www.knubisoft.com/e2e/testing/model/scenario}nonEmptyString" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "postgresResult", propOrder = {
        "query"
})
public class PostgresResult
        extends AbstractCommand {

    @XmlElement(required = true)
    protected String query;
    @XmlAttribute(name = "file")
    protected String file;
    @XmlAttribute(name = "databaseName", required = true)
    protected String databaseName;

    /**
     * Gets the value of the query property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getQuery() {
        return query;
    }

    /**
     * Sets the value of the query property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQuery(String value) {
        this.query = value;
    }

    /**
     * Gets the value of the file property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFile(String value) {
        this.file = value;
    }

    /**
     * Gets the value of the databaseName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDatabaseName() {
        return databaseName;
    }

    /**
     * Sets the value of the databaseName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDatabaseName(String value) {
        this.databaseName = value;
    }

}
