//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.08 at 09:58:30 AM EEST 
//


package com.knubisoft.e2e.testing.model.scenario;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scrollToElementBy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="scrollToElementBy"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="by text"/&gt;
 *     &lt;enumeration value="by xpath"/&gt;
 *     &lt;enumeration value="by Id"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "scrollToElementBy")
@XmlEnum
public enum ScrollToElementBy {

    @XmlEnumValue("by text")
    BY_TEXT("by text"),
    @XmlEnumValue("by xpath")
    BY_XPATH("by xpath"),
    @XmlEnumValue("by Id")
    BY_ID("by Id");
    private final String value;

    ScrollToElementBy(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScrollToElementBy fromValue(String v) {
        for (ScrollToElementBy c: ScrollToElementBy.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
