//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.16 at 10:39:28 PM EET 
//


package com.knubisoft.e2e.testing.model.scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sendgrid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sendgrid"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.knubisoft.com/e2e/testing/model/scenario}abstractCommand"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="get" type="{http://www.knubisoft.com/e2e/testing/model/scenario}sendgridGet"/&gt;
 *           &lt;element name="post" type="{http://www.knubisoft.com/e2e/testing/model/scenario}sendgridPost"/&gt;
 *           &lt;element name="put" type="{http://www.knubisoft.com/e2e/testing/model/scenario}sendgridPut"/&gt;
 *           &lt;element name="patch" type="{http://www.knubisoft.com/e2e/testing/model/scenario}sendgridPatch"/&gt;
 *           &lt;element name="delete" type="{http://www.knubisoft.com/e2e/testing/model/scenario}sendgridDelete"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="alias" use="required" type="{http://www.knubisoft.com/e2e/testing/model/scenario}nonEmptyString" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendgrid", propOrder = {
    "get",
    "post",
    "put",
    "patch",
    "delete"
})
public class Sendgrid
    extends AbstractCommand
{

    protected SendgridGet get;
    protected SendgridPost post;
    protected SendgridPut put;
    protected SendgridPatch patch;
    protected SendgridDelete delete;
    @XmlAttribute(name = "alias", required = true)
    protected String alias;

    /**
     * Gets the value of the get property.
     * 
     * @return
     *     possible object is
     *     {@link SendgridGet }
     *     
     */
    public SendgridGet getGet() {
        return get;
    }

    /**
     * Sets the value of the get property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendgridGet }
     *     
     */
    public void setGet(SendgridGet value) {
        this.get = value;
    }

    /**
     * Gets the value of the post property.
     * 
     * @return
     *     possible object is
     *     {@link SendgridPost }
     *     
     */
    public SendgridPost getPost() {
        return post;
    }

    /**
     * Sets the value of the post property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendgridPost }
     *     
     */
    public void setPost(SendgridPost value) {
        this.post = value;
    }

    /**
     * Gets the value of the put property.
     * 
     * @return
     *     possible object is
     *     {@link SendgridPut }
     *     
     */
    public SendgridPut getPut() {
        return put;
    }

    /**
     * Sets the value of the put property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendgridPut }
     *     
     */
    public void setPut(SendgridPut value) {
        this.put = value;
    }

    /**
     * Gets the value of the patch property.
     * 
     * @return
     *     possible object is
     *     {@link SendgridPatch }
     *     
     */
    public SendgridPatch getPatch() {
        return patch;
    }

    /**
     * Sets the value of the patch property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendgridPatch }
     *     
     */
    public void setPatch(SendgridPatch value) {
        this.patch = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link SendgridDelete }
     *     
     */
    public SendgridDelete getDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendgridDelete }
     *     
     */
    public void setDelete(SendgridDelete value) {
        this.delete = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

}
