//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.15 at 04:20:29 PM EEST 
//


package com.knubisoft.e2e.testing.model.scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sesMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sesMessage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="body" type="{http://www.knubisoft.com/e2e/testing/model/scenario}sesBody"/&gt;
 *         &lt;element name="subject" type="{http://www.knubisoft.com/e2e/testing/model/scenario}sesTextContent"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sesMessage", propOrder = {
    "body",
    "subject"
})
public class SesMessage {

    @XmlElement(required = true)
    protected SesBody body;
    @XmlElement(required = true)
    protected SesTextContent subject;

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link SesBody }
     *     
     */
    public SesBody getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link SesBody }
     *     
     */
    public void setBody(SesBody value) {
        this.body = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link SesTextContent }
     *     
     */
    public SesTextContent getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link SesTextContent }
     *     
     */
    public void setSubject(SesTextContent value) {
        this.subject = value;
    }

}
