//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.03 at 01:53:38 PM EET 
//


package com.knubisoft.e2e.testing.model.scenario;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for storageName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="storageName"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="POSTGRES"/&gt;
 *     &lt;enumeration value="MYSQL"/&gt;
 *     &lt;enumeration value="ORACLE"/&gt;
 *     &lt;enumeration value="REDIS"/&gt;
 *     &lt;enumeration value="MONGODB"/&gt;
 *     &lt;enumeration value="DYNAMO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "storageName")
@XmlEnum
public enum StorageName {

    POSTGRES,
    CLICKHOUSE,
    MYSQL,
    ORACLE,
    REDIS,
    MONGODB,
    DYNAMO;

    public String value() {
        return name();
    }

    public static StorageName fromValue(String v) {
        return valueOf(v);
    }

}
