//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.08 at 09:58:30 AM EEST 
//


package com.knubisoft.e2e.testing.model.scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for verticalAndHorizontal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="verticalAndHorizontal"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="by" use="required" type="{http://www.knubisoft.com/e2e/testing/model/scenario}scrollBy" /&gt;
 *       &lt;attribute name="hDirection" use="required" type="{http://www.knubisoft.com/e2e/testing/model/scenario}scrollHorizontalDir" /&gt;
 *       &lt;attribute name="horizontalValue" use="required" type="{http://www.knubisoft.com/e2e/testing/model/scenario}nonEmptyString" /&gt;
 *       &lt;attribute name="vDirection" use="required" type="{http://www.knubisoft.com/e2e/testing/model/scenario}scrollVerticalDir" /&gt;
 *       &lt;attribute name="verticalValue" use="required" type="{http://www.knubisoft.com/e2e/testing/model/scenario}nonEmptyString" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "verticalAndHorizontal")
public class VerticalAndHorizontal {

    @XmlAttribute(name = "by", required = true)
    protected ScrollBy by;
    @XmlAttribute(name = "hDirection", required = true)
    protected ScrollHorizontalDir hDirection;
    @XmlAttribute(name = "horizontalValue", required = true)
    protected String horizontalValue;
    @XmlAttribute(name = "vDirection", required = true)
    protected ScrollVerticalDir vDirection;
    @XmlAttribute(name = "verticalValue", required = true)
    protected String verticalValue;

    /**
     * Gets the value of the by property.
     * 
     * @return
     *     possible object is
     *     {@link ScrollBy }
     *     
     */
    public ScrollBy getBy() {
        return by;
    }

    /**
     * Sets the value of the by property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScrollBy }
     *     
     */
    public void setBy(ScrollBy value) {
        this.by = value;
    }

    /**
     * Gets the value of the hDirection property.
     * 
     * @return
     *     possible object is
     *     {@link ScrollHorizontalDir }
     *     
     */
    public ScrollHorizontalDir getHDirection() {
        return hDirection;
    }

    /**
     * Sets the value of the hDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScrollHorizontalDir }
     *     
     */
    public void setHDirection(ScrollHorizontalDir value) {
        this.hDirection = value;
    }

    /**
     * Gets the value of the horizontalValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorizontalValue() {
        return horizontalValue;
    }

    /**
     * Sets the value of the horizontalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorizontalValue(String value) {
        this.horizontalValue = value;
    }

    /**
     * Gets the value of the vDirection property.
     * 
     * @return
     *     possible object is
     *     {@link ScrollVerticalDir }
     *     
     */
    public ScrollVerticalDir getVDirection() {
        return vDirection;
    }

    /**
     * Sets the value of the vDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScrollVerticalDir }
     *     
     */
    public void setVDirection(ScrollVerticalDir value) {
        this.vDirection = value;
    }

    /**
     * Gets the value of the verticalValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalValue() {
        return verticalValue;
    }

    /**
     * Sets the value of the verticalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalValue(String value) {
        this.verticalValue = value;
    }

}
