//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.08 at 09:58:30 AM EEST 
//


package com.knubisoft.e2e.testing.model.scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vertical complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vertical"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="scrollByValue" type="{http://www.knubisoft.com/e2e/testing/model/scenario}verticalByValue"/&gt;
 *         &lt;element name="scrollToTopOrBottom" type="{http://www.knubisoft.com/e2e/testing/model/scenario}scrollToTopOrBottom"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vertical", propOrder = {
    "scrollByValue",
    "scrollToTopOrBottom"
})
public class Vertical {

    protected VerticalByValue scrollByValue;
    @XmlSchemaType(name = "string")
    protected ScrollToTopOrBottom scrollToTopOrBottom;

    /**
     * Gets the value of the scrollByValue property.
     * 
     * @return
     *     possible object is
     *     {@link VerticalByValue }
     *     
     */
    public VerticalByValue getScrollByValue() {
        return scrollByValue;
    }

    /**
     * Sets the value of the scrollByValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerticalByValue }
     *     
     */
    public void setScrollByValue(VerticalByValue value) {
        this.scrollByValue = value;
    }

    /**
     * Gets the value of the scrollToTopOrBottom property.
     * 
     * @return
     *     possible object is
     *     {@link ScrollToTopOrBottom }
     *     
     */
    public ScrollToTopOrBottom getScrollToTopOrBottom() {
        return scrollToTopOrBottom;
    }

    /**
     * Sets the value of the scrollToTopOrBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScrollToTopOrBottom }
     *     
     */
    public void setScrollToTopOrBottom(ScrollToTopOrBottom value) {
        this.scrollToTopOrBottom = value;
    }

}
