//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.12 at 02:06:55 PM EEST 
//


package com.knubisoft.cott.testing.model.scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for elasticsearch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="elasticsearch"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.knubisoft.com/cott/testing/model/scenario}abstractCommand"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="get" type="{http://www.knubisoft.com/cott/testing/model/scenario}elasticsearchGetRequest"/&gt;
 *         &lt;element name="post" type="{http://www.knubisoft.com/cott/testing/model/scenario}elasticsearchPostRequest"/&gt;
 *         &lt;element name="put" type="{http://www.knubisoft.com/cott/testing/model/scenario}elasticsearchPutRequest"/&gt;
 *         &lt;element name="patch" type="{http://www.knubisoft.com/cott/testing/model/scenario}elasticsearchPatchRequest"/&gt;
 *         &lt;element name="delete" type="{http://www.knubisoft.com/cott/testing/model/scenario}elasticsearchDeleteRequest"/&gt;
 *         &lt;element name="options" type="{http://www.knubisoft.com/cott/testing/model/scenario}elasticsearchOptionsRequest"/&gt;
 *         &lt;element name="head" type="{http://www.knubisoft.com/cott/testing/model/scenario}elasticsearchHeadRequest"/&gt;
 *         &lt;element name="trace" type="{http://www.knubisoft.com/cott/testing/model/scenario}elasticsearchTraceRequest"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="alias" use="required" type="{http://www.knubisoft.com/cott/testing/model/scenario}nonEmptyString" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elasticsearch", propOrder = {
    "get",
    "post",
    "put",
    "patch",
    "delete",
    "options",
    "head",
    "trace"
})
public class Elasticsearch
    extends AbstractCommand
{

    protected ElasticsearchGetRequest get;
    protected ElasticsearchPostRequest post;
    protected ElasticsearchPutRequest put;
    protected ElasticsearchPatchRequest patch;
    protected ElasticsearchDeleteRequest delete;
    protected ElasticsearchOptionsRequest options;
    protected ElasticsearchHeadRequest head;
    protected ElasticsearchTraceRequest trace;
    @XmlAttribute(name = "alias", required = true)
    protected String alias;

    /**
     * Gets the value of the get property.
     * 
     * @return
     *     possible object is
     *     {@link ElasticsearchGetRequest }
     *     
     */
    public ElasticsearchGetRequest getGet() {
        return get;
    }

    /**
     * Sets the value of the get property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElasticsearchGetRequest }
     *     
     */
    public void setGet(ElasticsearchGetRequest value) {
        this.get = value;
    }

    /**
     * Gets the value of the post property.
     * 
     * @return
     *     possible object is
     *     {@link ElasticsearchPostRequest }
     *     
     */
    public ElasticsearchPostRequest getPost() {
        return post;
    }

    /**
     * Sets the value of the post property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElasticsearchPostRequest }
     *     
     */
    public void setPost(ElasticsearchPostRequest value) {
        this.post = value;
    }

    /**
     * Gets the value of the put property.
     * 
     * @return
     *     possible object is
     *     {@link ElasticsearchPutRequest }
     *     
     */
    public ElasticsearchPutRequest getPut() {
        return put;
    }

    /**
     * Sets the value of the put property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElasticsearchPutRequest }
     *     
     */
    public void setPut(ElasticsearchPutRequest value) {
        this.put = value;
    }

    /**
     * Gets the value of the patch property.
     * 
     * @return
     *     possible object is
     *     {@link ElasticsearchPatchRequest }
     *     
     */
    public ElasticsearchPatchRequest getPatch() {
        return patch;
    }

    /**
     * Sets the value of the patch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElasticsearchPatchRequest }
     *     
     */
    public void setPatch(ElasticsearchPatchRequest value) {
        this.patch = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link ElasticsearchDeleteRequest }
     *     
     */
    public ElasticsearchDeleteRequest getDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElasticsearchDeleteRequest }
     *     
     */
    public void setDelete(ElasticsearchDeleteRequest value) {
        this.delete = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link ElasticsearchOptionsRequest }
     *     
     */
    public ElasticsearchOptionsRequest getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElasticsearchOptionsRequest }
     *     
     */
    public void setOptions(ElasticsearchOptionsRequest value) {
        this.options = value;
    }

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link ElasticsearchHeadRequest }
     *     
     */
    public ElasticsearchHeadRequest getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElasticsearchHeadRequest }
     *     
     */
    public void setHead(ElasticsearchHeadRequest value) {
        this.head = value;
    }

    /**
     * Gets the value of the trace property.
     * 
     * @return
     *     possible object is
     *     {@link ElasticsearchTraceRequest }
     *     
     */
    public ElasticsearchTraceRequest getTrace() {
        return trace;
    }

    /**
     * Sets the value of the trace property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElasticsearchTraceRequest }
     *     
     */
    public void setTrace(ElasticsearchTraceRequest value) {
        this.trace = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

}
