//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.04 at 06:55:39 PM CEST 
//


package com.knubisoft.cott.testing.model.scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for var complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="var"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.knubisoft.com/cott/testing/model/scenario}abstractCommand"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="dbResult" type="{http://www.knubisoft.com/cott/testing/model/scenario}dbResult"/&gt;
 *         &lt;element name="pageResult" type="{http://www.knubisoft.com/cott/testing/model/scenario}pageRequest"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.knubisoft.com/cott/testing/model/scenario}nonEmptyString" /&gt;
 *       &lt;attribute name="alias" type="{http://www.knubisoft.com/cott/testing/model/scenario}nonEmptyString" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "var", propOrder = {
    "dbResult",
    "pageResult"
})
public class Var
    extends AbstractCommand
{

    protected DbResult dbResult;
    protected PageRequest pageResult;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "alias")
    protected String alias;

    /**
     * Gets the value of the dbResult property.
     * 
     * @return
     *     possible object is
     *     {@link DbResult }
     *     
     */
    public DbResult getDbResult() {
        return dbResult;
    }

    /**
     * Sets the value of the dbResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbResult }
     *     
     */
    public void setDbResult(DbResult value) {
        this.dbResult = value;
    }

    /**
     * Gets the value of the pageResult property.
     * 
     * @return
     *     possible object is
     *     {@link PageRequest }
     *     
     */
    public PageRequest getPageResult() {
        return pageResult;
    }

    /**
     * Sets the value of the pageResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageRequest }
     *     
     */
    public void setPageResult(PageRequest value) {
        this.pageResult = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

}
