//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.20 at 11:58:21 AM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for abstractBrowser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="abstractBrowser"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="browserType" type="{http://www.knubisoft.com/e2e/testing/model/global-config}browserType"/&gt;
 *         &lt;element name="capabilities" type="{http://www.knubisoft.com/e2e/testing/model/global-config}capabilities" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="enable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="maximizedBrowserWindow" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="browserWindowSize" type="{http://www.knubisoft.com/e2e/testing/model/global-config}windowSize" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstractBrowser", propOrder = {
    "browserType",
    "capabilities"
})
@XmlSeeAlso({
    Chrome.class,
    Firefox.class,
    Edge.class,
    Opera.class,
    Safari.class
})
public abstract class AbstractBrowser {

    @XmlElement(required = true)
    protected BrowserType browserType;
    protected Capabilities capabilities;
    @XmlAttribute(name = "enable", required = true)
    protected boolean enable;
    @XmlAttribute(name = "maximizedBrowserWindow", required = true)
    protected boolean maximizedBrowserWindow;
    @XmlAttribute(name = "browserWindowSize")
    protected String browserWindowSize;

    /**
     * Gets the value of the browserType property.
     * 
     * @return
     *     possible object is
     *     {@link BrowserType }
     *     
     */
    public BrowserType getBrowserType() {
        return browserType;
    }

    /**
     * Sets the value of the browserType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrowserType }
     *     
     */
    public void setBrowserType(BrowserType value) {
        this.browserType = value;
    }

    /**
     * Gets the value of the capabilities property.
     * 
     * @return
     *     possible object is
     *     {@link Capabilities }
     *     
     */
    public Capabilities getCapabilities() {
        return capabilities;
    }

    /**
     * Sets the value of the capabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Capabilities }
     *     
     */
    public void setCapabilities(Capabilities value) {
        this.capabilities = value;
    }

    /**
     * Gets the value of the enable property.
     * 
     */
    public boolean isEnable() {
        return enable;
    }

    /**
     * Sets the value of the enable property.
     * 
     */
    public void setEnable(boolean value) {
        this.enable = value;
    }

    /**
     * Gets the value of the maximizedBrowserWindow property.
     * 
     */
    public boolean isMaximizedBrowserWindow() {
        return maximizedBrowserWindow;
    }

    /**
     * Sets the value of the maximizedBrowserWindow property.
     * 
     */
    public void setMaximizedBrowserWindow(boolean value) {
        this.maximizedBrowserWindow = value;
    }

    /**
     * Gets the value of the browserWindowSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrowserWindowSize() {
        return browserWindowSize;
    }

    /**
     * Sets the value of the browserWindowSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrowserWindowSize(String value) {
        this.browserWindowSize = value;
    }

}
