//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.31 at 08:19:32 PM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for abstractBrowser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="abstractBrowser"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="webDriverVersion" type="{http://www.knubisoft.com/e2e/testing/model/global-config}webDriverVersion"/&gt;
 *         &lt;element name="webDriverOptions" type="{http://www.knubisoft.com/e2e/testing/model/global-config}webDriverOptions"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="enable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstractBrowser", propOrder = {
    "webDriverVersion",
    "webDriverOptions"
})
@XmlSeeAlso({
    Chrome.class,
    Firefox.class,
    Safari.class,
    Edge.class,
    Opera.class
})
public abstract class AbstractBrowser {

    @XmlElement(required = true)
    protected WebDriverVersion webDriverVersion;
    @XmlElement(required = true)
    protected WebDriverOptions webDriverOptions;
    @XmlAttribute(name = "enable", required = true)
    protected boolean enable;

    /**
     * Gets the value of the webDriverVersion property.
     * 
     * @return
     *     possible object is
     *     {@link WebDriverVersion }
     *     
     */
    public WebDriverVersion getWebDriverVersion() {
        return webDriverVersion;
    }

    /**
     * Sets the value of the webDriverVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebDriverVersion }
     *     
     */
    public void setWebDriverVersion(WebDriverVersion value) {
        this.webDriverVersion = value;
    }

    /**
     * Gets the value of the webDriverOptions property.
     * 
     * @return
     *     possible object is
     *     {@link WebDriverOptions }
     *     
     */
    public WebDriverOptions getWebDriverOptions() {
        return webDriverOptions;
    }

    /**
     * Sets the value of the webDriverOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebDriverOptions }
     *     
     */
    public void setWebDriverOptions(WebDriverOptions value) {
        this.webDriverOptions = value;
    }

    /**
     * Gets the value of the enable property.
     * 
     */
    public boolean isEnable() {
        return enable;
    }

    /**
     * Sets the value of the enable property.
     * 
     */
    public void setEnable(boolean value) {
        this.enable = value;
    }

}
