//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.06 at 07:16:04 PM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for auth complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="auth"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="authStrategy" type="{http://www.knubisoft.com/e2e/testing/model/global-config}authStrategies"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="autoLogout" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "auth", propOrder = {
    "authStrategy"
})
public class Auth {

    @XmlSchemaType(name = "string")
    protected AuthStrategies authStrategy;
    @XmlAttribute(name = "autoLogout")
    protected Boolean autoLogout;

    /**
     * Gets the value of the authStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link AuthStrategies }
     *     
     */
    public AuthStrategies getAuthStrategy() {
        return authStrategy;
    }

    /**
     * Sets the value of the authStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthStrategies }
     *     
     */
    public void setAuthStrategy(AuthStrategies value) {
        this.authStrategy = value;
    }

    /**
     * Gets the value of the autoLogout property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAutoLogout() {
        if (autoLogout == null) {
            return true;
        } else {
            return autoLogout;
        }
    }

    /**
     * Sets the value of the autoLogout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoLogout(Boolean value) {
        this.autoLogout = value;
    }

}
