//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.06 at 09:11:40 AM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for auth complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="auth"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="clearLocalStorage" type="{http://www.knubisoft.com/e2e/testing/model/global-config}clearLocalStorage" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="basic" type="{http://www.knubisoft.com/e2e/testing/model/global-config}basic"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="autoLogout" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="clearCookies" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "auth", propOrder = {
    "clearLocalStorage",
    "basic"
})
public class Auth {

    protected ClearLocalStorage clearLocalStorage;
    protected Basic basic;
    @XmlAttribute(name = "autoLogout")
    protected Boolean autoLogout;
    @XmlAttribute(name = "clearCookies")
    protected Boolean clearCookies;

    /**
     * Gets the value of the clearLocalStorage property.
     * 
     * @return
     *     possible object is
     *     {@link ClearLocalStorage }
     *     
     */
    public ClearLocalStorage getClearLocalStorage() {
        return clearLocalStorage;
    }

    /**
     * Sets the value of the clearLocalStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearLocalStorage }
     *     
     */
    public void setClearLocalStorage(ClearLocalStorage value) {
        this.clearLocalStorage = value;
    }

    /**
     * Gets the value of the basic property.
     * 
     * @return
     *     possible object is
     *     {@link Basic }
     *     
     */
    public Basic getBasic() {
        return basic;
    }

    /**
     * Sets the value of the basic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Basic }
     *     
     */
    public void setBasic(Basic value) {
        this.basic = value;
    }

    /**
     * Gets the value of the autoLogout property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAutoLogout() {
        if (autoLogout == null) {
            return true;
        } else {
            return autoLogout;
        }
    }

    /**
     * Sets the value of the autoLogout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoLogout(Boolean value) {
        this.autoLogout = value;
    }

    /**
     * Gets the value of the clearCookies property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isClearCookies() {
        if (clearCookies == null) {
            return true;
        } else {
            return clearCookies;
        }
    }

    /**
     * Sets the value of the clearCookies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClearCookies(Boolean value) {
        this.clearCookies = value;
    }

}
