//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.20 at 11:58:21 AM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for browserSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="browserSettings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="takeScreenshotOfEachUiCommand" type="{http://www.knubisoft.com/e2e/testing/model/global-config}takeScreenshotOfEachUiCommand"/&gt;
 *         &lt;element name="webElementAutowait" type="{http://www.knubisoft.com/e2e/testing/model/global-config}webElementAutowait"/&gt;
 *         &lt;element name="browsers" type="{http://www.knubisoft.com/e2e/testing/model/global-config}browsers"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "browserSettings", propOrder = {
    "takeScreenshotOfEachUiCommand",
    "webElementAutowait",
    "browsers"
})
public class BrowserSettings {

    @XmlElement(required = true)
    protected TakeScreenshotOfEachUiCommand takeScreenshotOfEachUiCommand;
    @XmlElement(required = true)
    protected WebElementAutowait webElementAutowait;
    @XmlElement(required = true)
    protected Browsers browsers;

    /**
     * Gets the value of the takeScreenshotOfEachUiCommand property.
     * 
     * @return
     *     possible object is
     *     {@link TakeScreenshotOfEachUiCommand }
     *     
     */
    public TakeScreenshotOfEachUiCommand getTakeScreenshotOfEachUiCommand() {
        return takeScreenshotOfEachUiCommand;
    }

    /**
     * Sets the value of the takeScreenshotOfEachUiCommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link TakeScreenshotOfEachUiCommand }
     *     
     */
    public void setTakeScreenshotOfEachUiCommand(TakeScreenshotOfEachUiCommand value) {
        this.takeScreenshotOfEachUiCommand = value;
    }

    /**
     * Gets the value of the webElementAutowait property.
     * 
     * @return
     *     possible object is
     *     {@link WebElementAutowait }
     *     
     */
    public WebElementAutowait getWebElementAutowait() {
        return webElementAutowait;
    }

    /**
     * Sets the value of the webElementAutowait property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebElementAutowait }
     *     
     */
    public void setWebElementAutowait(WebElementAutowait value) {
        this.webElementAutowait = value;
    }

    /**
     * Gets the value of the browsers property.
     * 
     * @return
     *     possible object is
     *     {@link Browsers }
     *     
     */
    public Browsers getBrowsers() {
        return browsers;
    }

    /**
     * Sets the value of the browsers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Browsers }
     *     
     */
    public void setBrowsers(Browsers value) {
        this.browsers = value;
    }

}
