//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.10 at 03:23:27 PM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chrome complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chrome"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.knubisoft.com/e2e/testing/model/global-config}abstractBrowser"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="chromeOptionsArguments" type="{http://www.knubisoft.com/e2e/testing/model/global-config}browserOptionsArguments" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="setHeadless" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chrome", propOrder = {
    "chromeOptionsArguments"
})
public class Chrome
    extends AbstractBrowser
{

    protected BrowserOptionsArguments chromeOptionsArguments;
    @XmlAttribute(name = "setHeadless", required = true)
    protected boolean setHeadless;

    /**
     * Gets the value of the chromeOptionsArguments property.
     * 
     * @return
     *     possible object is
     *     {@link BrowserOptionsArguments }
     *     
     */
    public BrowserOptionsArguments getChromeOptionsArguments() {
        return chromeOptionsArguments;
    }

    /**
     * Sets the value of the chromeOptionsArguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrowserOptionsArguments }
     *     
     */
    public void setChromeOptionsArguments(BrowserOptionsArguments value) {
        this.chromeOptionsArguments = value;
    }

    /**
     * Gets the value of the setHeadless property.
     * 
     */
    public boolean isSetHeadless() {
        return setHeadless;
    }

    /**
     * Sets the value of the setHeadless property.
     * 
     */
    public void setSetHeadless(boolean value) {
        this.setHeadless = value;
    }

}
