//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.31 at 08:19:32 PM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="stopScenarioOnFailure" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="localStorageAuthorizationKey" type="{http://www.knubisoft.com/e2e/testing/model/global-config}nonEmptyString"/&gt;
 *         &lt;element name="filterDirectoryPattern" type="{http://www.knubisoft.com/e2e/testing/model/global-config}nonEmptyString"/&gt;
 *         &lt;element name="debugMode" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="filterTags" type="{http://www.knubisoft.com/e2e/testing/model/global-config}filterTags"/&gt;
 *         &lt;element name="parallelExecution" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="parallelExecutionLimit" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ui" type="{http://www.knubisoft.com/e2e/testing/model/global-config}ui" minOccurs="0"/&gt;
 *         &lt;element name="integrations" type="{http://www.knubisoft.com/e2e/testing/model/global-config}integrations" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stopScenarioOnFailure",
    "localStorageAuthorizationKey",
    "filterDirectoryPattern",
    "debugMode",
    "filterTags",
    "parallelExecution",
    "parallelExecutionLimit",
    "ui",
    "integrations"
})
@XmlRootElement(name = "globalTestConfiguration")
public class GlobalTestConfiguration {

    protected boolean stopScenarioOnFailure;
    @XmlElement(required = true)
    protected String localStorageAuthorizationKey;
    @XmlElement(required = true)
    protected String filterDirectoryPattern;
    protected boolean debugMode;
    @XmlElement(required = true)
    protected FilterTags filterTags;
    protected boolean parallelExecution;
    protected int parallelExecutionLimit;
    protected Ui ui;
    protected Integrations integrations;

    /**
     * Gets the value of the stopScenarioOnFailure property.
     * 
     */
    public boolean isStopScenarioOnFailure() {
        return stopScenarioOnFailure;
    }

    /**
     * Sets the value of the stopScenarioOnFailure property.
     * 
     */
    public void setStopScenarioOnFailure(boolean value) {
        this.stopScenarioOnFailure = value;
    }

    /**
     * Gets the value of the localStorageAuthorizationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalStorageAuthorizationKey() {
        return localStorageAuthorizationKey;
    }

    /**
     * Sets the value of the localStorageAuthorizationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalStorageAuthorizationKey(String value) {
        this.localStorageAuthorizationKey = value;
    }

    /**
     * Gets the value of the filterDirectoryPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilterDirectoryPattern() {
        return filterDirectoryPattern;
    }

    /**
     * Sets the value of the filterDirectoryPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilterDirectoryPattern(String value) {
        this.filterDirectoryPattern = value;
    }

    /**
     * Gets the value of the debugMode property.
     * 
     */
    public boolean isDebugMode() {
        return debugMode;
    }

    /**
     * Sets the value of the debugMode property.
     * 
     */
    public void setDebugMode(boolean value) {
        this.debugMode = value;
    }

    /**
     * Gets the value of the filterTags property.
     * 
     * @return
     *     possible object is
     *     {@link FilterTags }
     *     
     */
    public FilterTags getFilterTags() {
        return filterTags;
    }

    /**
     * Sets the value of the filterTags property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterTags }
     *     
     */
    public void setFilterTags(FilterTags value) {
        this.filterTags = value;
    }

    /**
     * Gets the value of the parallelExecution property.
     * 
     */
    public boolean isParallelExecution() {
        return parallelExecution;
    }

    /**
     * Sets the value of the parallelExecution property.
     * 
     */
    public void setParallelExecution(boolean value) {
        this.parallelExecution = value;
    }

    /**
     * Gets the value of the parallelExecutionLimit property.
     * 
     */
    public int getParallelExecutionLimit() {
        return parallelExecutionLimit;
    }

    /**
     * Sets the value of the parallelExecutionLimit property.
     * 
     */
    public void setParallelExecutionLimit(int value) {
        this.parallelExecutionLimit = value;
    }

    /**
     * Gets the value of the ui property.
     * 
     * @return
     *     possible object is
     *     {@link Ui }
     *     
     */
    public Ui getUi() {
        return ui;
    }

    /**
     * Sets the value of the ui property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ui }
     *     
     */
    public void setUi(Ui value) {
        this.ui = value;
    }

    /**
     * Gets the value of the integrations property.
     * 
     * @return
     *     possible object is
     *     {@link Integrations }
     *     
     */
    public Integrations getIntegrations() {
        return integrations;
    }

    /**
     * Sets the value of the integrations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integrations }
     *     
     */
    public void setIntegrations(Integrations value) {
        this.integrations = value;
    }

}
