//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.09 at 07:56:34 PM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for integrations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="integrations"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="apis" type="{http://www.knubisoft.com/e2e/testing/model/global-config}apis" minOccurs="0"/&gt;
 *         &lt;element name="postgreses" type="{http://www.knubisoft.com/e2e/testing/model/global-config}postgreses" minOccurs="0"/&gt;
 *         &lt;element name="clickhouses" type="{http://www.knubisoft.com/e2e/testing/model/global-config}clickhouses" minOccurs="0"/&gt;
 *         &lt;element name="mysqls" type="{http://www.knubisoft.com/e2e/testing/model/global-config}mysqls" minOccurs="0"/&gt;
 *         &lt;element name="oracles" type="{http://www.knubisoft.com/e2e/testing/model/global-config}oracles" minOccurs="0"/&gt;
 *         &lt;element name="redises" type="{http://www.knubisoft.com/e2e/testing/model/global-config}redises" minOccurs="0"/&gt;
 *         &lt;element name="mongos" type="{http://www.knubisoft.com/e2e/testing/model/global-config}mongos" minOccurs="0"/&gt;
 *         &lt;element name="s3s" type="{http://www.knubisoft.com/e2e/testing/model/global-config}s3s" minOccurs="0"/&gt;
 *         &lt;element name="sqss" type="{http://www.knubisoft.com/e2e/testing/model/global-config}sqss" minOccurs="0"/&gt;
 *         &lt;element name="kafkas" type="{http://www.knubisoft.com/e2e/testing/model/global-config}kafkas" minOccurs="0"/&gt;
 *         &lt;element name="rabbitmqs" type="{http://www.knubisoft.com/e2e/testing/model/global-config}rabbitmqs" minOccurs="0"/&gt;
 *         &lt;element name="dynamos" type="{http://www.knubisoft.com/e2e/testing/model/global-config}dynamos" minOccurs="0"/&gt;
 *         &lt;element name="elasticsearches" type="{http://www.knubisoft.com/e2e/testing/model/global-config}elasticsearches" minOccurs="0"/&gt;
 *         &lt;element name="sendgrids" type="{http://www.knubisoft.com/e2e/testing/model/global-config}sendgrids" minOccurs="0"/&gt;
 *         &lt;element name="seses" type="{http://www.knubisoft.com/e2e/testing/model/global-config}seses" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "integrations", propOrder = {

})
public class Integrations {

    protected Apis apis;
    protected Postgreses postgreses;
    protected Clickhouses clickhouses;
    protected Mysqls mysqls;
    protected Oracles oracles;
    protected Redises redises;
    protected Mongos mongos;
    @XmlElement(name = "s3s")
    protected S3S s3S;
    protected Sqss sqss;
    protected Kafkas kafkas;
    protected Rabbitmqs rabbitmqs;
    protected Dynamos dynamos;
    protected Elasticsearches elasticsearches;
    protected Sendgrids sendgrids;
    protected Seses seses;

    /**
     * Gets the value of the apis property.
     * 
     * @return
     *     possible object is
     *     {@link Apis }
     *     
     */
    public Apis getApis() {
        return apis;
    }

    /**
     * Sets the value of the apis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Apis }
     *     
     */
    public void setApis(Apis value) {
        this.apis = value;
    }

    /**
     * Gets the value of the postgreses property.
     * 
     * @return
     *     possible object is
     *     {@link Postgreses }
     *     
     */
    public Postgreses getPostgreses() {
        return postgreses;
    }

    /**
     * Sets the value of the postgreses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Postgreses }
     *     
     */
    public void setPostgreses(Postgreses value) {
        this.postgreses = value;
    }

    /**
     * Gets the value of the clickhouses property.
     * 
     * @return
     *     possible object is
     *     {@link Clickhouses }
     *     
     */
    public Clickhouses getClickhouses() {
        return clickhouses;
    }

    /**
     * Sets the value of the clickhouses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clickhouses }
     *     
     */
    public void setClickhouses(Clickhouses value) {
        this.clickhouses = value;
    }

    /**
     * Gets the value of the mysqls property.
     * 
     * @return
     *     possible object is
     *     {@link Mysqls }
     *     
     */
    public Mysqls getMysqls() {
        return mysqls;
    }

    /**
     * Sets the value of the mysqls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mysqls }
     *     
     */
    public void setMysqls(Mysqls value) {
        this.mysqls = value;
    }

    /**
     * Gets the value of the oracles property.
     * 
     * @return
     *     possible object is
     *     {@link Oracles }
     *     
     */
    public Oracles getOracles() {
        return oracles;
    }

    /**
     * Sets the value of the oracles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Oracles }
     *     
     */
    public void setOracles(Oracles value) {
        this.oracles = value;
    }

    /**
     * Gets the value of the redises property.
     * 
     * @return
     *     possible object is
     *     {@link Redises }
     *     
     */
    public Redises getRedises() {
        return redises;
    }

    /**
     * Sets the value of the redises property.
     * 
     * @param value
     *     allowed object is
     *     {@link Redises }
     *     
     */
    public void setRedises(Redises value) {
        this.redises = value;
    }

    /**
     * Gets the value of the mongos property.
     * 
     * @return
     *     possible object is
     *     {@link Mongos }
     *     
     */
    public Mongos getMongos() {
        return mongos;
    }

    /**
     * Sets the value of the mongos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mongos }
     *     
     */
    public void setMongos(Mongos value) {
        this.mongos = value;
    }

    /**
     * Gets the value of the s3S property.
     * 
     * @return
     *     possible object is
     *     {@link S3S }
     *     
     */
    public S3S getS3S() {
        return s3S;
    }

    /**
     * Sets the value of the s3S property.
     * 
     * @param value
     *     allowed object is
     *     {@link S3S }
     *     
     */
    public void setS3S(S3S value) {
        this.s3S = value;
    }

    /**
     * Gets the value of the sqss property.
     * 
     * @return
     *     possible object is
     *     {@link Sqss }
     *     
     */
    public Sqss getSqss() {
        return sqss;
    }

    /**
     * Sets the value of the sqss property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sqss }
     *     
     */
    public void setSqss(Sqss value) {
        this.sqss = value;
    }

    /**
     * Gets the value of the kafkas property.
     * 
     * @return
     *     possible object is
     *     {@link Kafkas }
     *     
     */
    public Kafkas getKafkas() {
        return kafkas;
    }

    /**
     * Sets the value of the kafkas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kafkas }
     *     
     */
    public void setKafkas(Kafkas value) {
        this.kafkas = value;
    }

    /**
     * Gets the value of the rabbitmqs property.
     * 
     * @return
     *     possible object is
     *     {@link Rabbitmqs }
     *     
     */
    public Rabbitmqs getRabbitmqs() {
        return rabbitmqs;
    }

    /**
     * Sets the value of the rabbitmqs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rabbitmqs }
     *     
     */
    public void setRabbitmqs(Rabbitmqs value) {
        this.rabbitmqs = value;
    }

    /**
     * Gets the value of the dynamos property.
     * 
     * @return
     *     possible object is
     *     {@link Dynamos }
     *     
     */
    public Dynamos getDynamos() {
        return dynamos;
    }

    /**
     * Sets the value of the dynamos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dynamos }
     *     
     */
    public void setDynamos(Dynamos value) {
        this.dynamos = value;
    }

    /**
     * Gets the value of the elasticsearches property.
     * 
     * @return
     *     possible object is
     *     {@link Elasticsearches }
     *     
     */
    public Elasticsearches getElasticsearches() {
        return elasticsearches;
    }

    /**
     * Sets the value of the elasticsearches property.
     * 
     * @param value
     *     allowed object is
     *     {@link Elasticsearches }
     *     
     */
    public void setElasticsearches(Elasticsearches value) {
        this.elasticsearches = value;
    }

    /**
     * Gets the value of the sendgrids property.
     * 
     * @return
     *     possible object is
     *     {@link Sendgrids }
     *     
     */
    public Sendgrids getSendgrids() {
        return sendgrids;
    }

    /**
     * Sets the value of the sendgrids property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sendgrids }
     *     
     */
    public void setSendgrids(Sendgrids value) {
        this.sendgrids = value;
    }

    /**
     * Gets the value of the seses property.
     * 
     * @return
     *     possible object is
     *     {@link Seses }
     *     
     */
    public Seses getSeses() {
        return seses;
    }

    /**
     * Sets the value of the seses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Seses }
     *     
     */
    public void setSeses(Seses value) {
        this.seses = value;
    }

}
