//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.01 at 08:23:51 PM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for kafka complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="kafka"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bootstrapAddress" type="{http://www.knubisoft.com/e2e/testing/model/global-config}nonEmptyString"/&gt;
 *         &lt;element name="autoOffsetReset" type="{http://www.knubisoft.com/e2e/testing/model/global-config}nonEmptyString"/&gt;
 *         &lt;element name="maxPollRecords" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="maxPollIntervalMs" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="clientId" type="{http://www.knubisoft.com/e2e/testing/model/global-config}nonEmptyString"/&gt;
 *         &lt;element name="groupId" type="{http://www.knubisoft.com/e2e/testing/model/global-config}nonEmptyString"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="alias" use="required" type="{http://www.knubisoft.com/e2e/testing/model/global-config}nonEmptyString" /&gt;
 *       &lt;attribute name="enabled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kafka", propOrder = {
    "bootstrapAddress",
    "autoOffsetReset",
    "maxPollRecords",
    "maxPollIntervalMs",
    "clientId",
    "groupId"
})
public class Kafka {

    @XmlElement(required = true)
    protected String bootstrapAddress;
    @XmlElement(required = true)
    protected String autoOffsetReset;
    protected int maxPollRecords;
    protected int maxPollIntervalMs;
    @XmlElement(required = true)
    protected String clientId;
    @XmlElement(required = true)
    protected String groupId;
    @XmlAttribute(name = "alias", required = true)
    protected String alias;
    @XmlAttribute(name = "enabled", required = true)
    protected boolean enabled;

    /**
     * Gets the value of the bootstrapAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBootstrapAddress() {
        return bootstrapAddress;
    }

    /**
     * Sets the value of the bootstrapAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBootstrapAddress(String value) {
        this.bootstrapAddress = value;
    }

    /**
     * Gets the value of the autoOffsetReset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoOffsetReset() {
        return autoOffsetReset;
    }

    /**
     * Sets the value of the autoOffsetReset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoOffsetReset(String value) {
        this.autoOffsetReset = value;
    }

    /**
     * Gets the value of the maxPollRecords property.
     * 
     */
    public int getMaxPollRecords() {
        return maxPollRecords;
    }

    /**
     * Sets the value of the maxPollRecords property.
     * 
     */
    public void setMaxPollRecords(int value) {
        this.maxPollRecords = value;
    }

    /**
     * Gets the value of the maxPollIntervalMs property.
     * 
     */
    public int getMaxPollIntervalMs() {
        return maxPollIntervalMs;
    }

    /**
     * Sets the value of the maxPollIntervalMs property.
     * 
     */
    public void setMaxPollIntervalMs(int value) {
        this.maxPollIntervalMs = value;
    }

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

}
