//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.11 at 03:55:00 PM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for klovServerReportGenerator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="klovServerReportGenerator"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mongoDB" type="{http://www.knubisoft.com/e2e/testing/model/global-config}mongodb"/&gt;
 *         &lt;element name="klovServer" type="{http://www.knubisoft.com/e2e/testing/model/global-config}klovServer"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="enable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "klovServerReportGenerator", propOrder = {
    "mongoDB",
    "klovServer"
})
public class KlovServerReportGenerator {

    @XmlElement(required = true)
    protected Mongodb mongoDB;
    @XmlElement(required = true)
    protected KlovServer klovServer;
    @XmlAttribute(name = "enable", required = true)
    protected boolean enable;

    /**
     * Gets the value of the mongoDB property.
     * 
     * @return
     *     possible object is
     *     {@link Mongodb }
     *     
     */
    public Mongodb getMongoDB() {
        return mongoDB;
    }

    /**
     * Sets the value of the mongoDB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mongodb }
     *     
     */
    public void setMongoDB(Mongodb value) {
        this.mongoDB = value;
    }

    /**
     * Gets the value of the klovServer property.
     * 
     * @return
     *     possible object is
     *     {@link KlovServer }
     *     
     */
    public KlovServer getKlovServer() {
        return klovServer;
    }

    /**
     * Sets the value of the klovServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link KlovServer }
     *     
     */
    public void setKlovServer(KlovServer value) {
        this.klovServer = value;
    }

    /**
     * Gets the value of the enable property.
     * 
     */
    public boolean isEnable() {
        return enable;
    }

    /**
     * Sets the value of the enable property.
     * 
     */
    public void setEnable(boolean value) {
        this.enable = value;
    }

}
