//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.10 at 03:23:27 PM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for locallyRunModeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="locallyRunModeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="onLocalMachine"/&gt;
 *     &lt;enumeration value="locallyInDocker"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "locallyRunModeType")
@XmlEnum
public enum LocallyRunModeType {

    @XmlEnumValue("onLocalMachine")
    ON_LOCAL_MACHINE("onLocalMachine"),
    @XmlEnumValue("locallyInDocker")
    LOCALLY_IN_DOCKER("locallyInDocker");
    private final String value;

    LocallyRunModeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LocallyRunModeType fromValue(String v) {
        for (LocallyRunModeType c: LocallyRunModeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
