//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.10 at 03:23:27 PM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for runMode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="runMode"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="locallyRunMode" type="{http://www.knubisoft.com/e2e/testing/model/global-config}locallyRunMode"/&gt;
 *         &lt;element name="remoteRunMode" type="{http://www.knubisoft.com/e2e/testing/model/global-config}remoteRunMode"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "runMode", propOrder = {
    "locallyRunMode",
    "remoteRunMode"
})
public class RunMode {

    protected LocallyRunMode locallyRunMode;
    protected RemoteRunMode remoteRunMode;

    /**
     * Gets the value of the locallyRunMode property.
     * 
     * @return
     *     possible object is
     *     {@link LocallyRunMode }
     *     
     */
    public LocallyRunMode getLocallyRunMode() {
        return locallyRunMode;
    }

    /**
     * Sets the value of the locallyRunMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocallyRunMode }
     *     
     */
    public void setLocallyRunMode(LocallyRunMode value) {
        this.locallyRunMode = value;
    }

    /**
     * Gets the value of the remoteRunMode property.
     * 
     * @return
     *     possible object is
     *     {@link RemoteRunMode }
     *     
     */
    public RemoteRunMode getRemoteRunMode() {
        return remoteRunMode;
    }

    /**
     * Sets the value of the remoteRunMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemoteRunMode }
     *     
     */
    public void setRemoteRunMode(RemoteRunMode value) {
        this.remoteRunMode = value;
    }

}
