//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.31 at 08:19:32 PM EEST 
//


package com.knubisoft.e2e.testing.model.global_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for webDriverRunMode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="webDriverRunMode"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="locally" type="{http://www.knubisoft.com/e2e/testing/model/global-config}locally"/&gt;
 *         &lt;element name="remote" type="{http://www.knubisoft.com/e2e/testing/model/global-config}remote"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "webDriverRunMode", propOrder = {
    "locally",
    "remote"
})
public class WebDriverRunMode {

    protected Locally locally;
    protected Remote remote;

    /**
     * Gets the value of the locally property.
     * 
     * @return
     *     possible object is
     *     {@link Locally }
     *     
     */
    public Locally getLocally() {
        return locally;
    }

    /**
     * Sets the value of the locally property.
     * 
     * @param value
     *     allowed object is
     *     {@link Locally }
     *     
     */
    public void setLocally(Locally value) {
        this.locally = value;
    }

    /**
     * Gets the value of the remote property.
     * 
     * @return
     *     possible object is
     *     {@link Remote }
     *     
     */
    public Remote getRemote() {
        return remote;
    }

    /**
     * Sets the value of the remote property.
     * 
     * @param value
     *     allowed object is
     *     {@link Remote }
     *     
     */
    public void setRemote(Remote value) {
        this.remote = value;
    }

}
