//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.15 at 04:20:29 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.knubisoft.com/e2e/testing/model/pages", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.knubisoft.e2e.testing.model.pages;
