//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.25 at 07:32:51 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.knubisoft.com/cott/testing/model/global-config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.knubisoft.cott.testing.model.global_config;
